##-----------------------------------------##
/run/verbose 1
/event/verbose 0
/tracking/verbose 0
##-----------------------------------------##
/target/length 10.0 mm
/target/width 50.0 mm
/target/height 50.0 mm
/output/filename ../output/output.root
/stack/killsecondaries 1
/beam/deltaP 0.01
/beam/P 4.0 GeV
/beam/pName e+
/beam/PdirX 0.0
/beam/PdirY 0.0
/beam/PdirZ 1.0

/run/initialize
##-----------------------------------------##
/vis/open HepRepFile
#/vis/open OGL #700x700-0+0

/vis/drawVolume
/vis/viewer/set/viewpointThetaPhi 90. 0.
/vis/scene/add/trajectories
/vis/scene/endOfEventAction accumulate 100
/vis/scene/add/trajectories rich smooth
/vis/modeling/trajectories/create/drawByCharge
/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts true
/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 5
/vis/modeling/trajectories/drawByCharge-0/default/setDrawAuxPts true
/vis/modeling/trajectories/drawByCharge-0/default/setAuxPtsSize 5
/vis/modeling/trajectories/drawByCharge-0/default/setTimeSliceInterval 0.1 ns
##-----------------------------------------##
/run/beamOn 30
##-----------------------------------------##
